version: "{build}"
os: Windows Server 2012 R2

test: off
deploy: off

init:
  - cmd: rd /s /q %CHOCOLATEYINSTALL%
  - ps: iex ((New-Object Net.WebClient).DownloadString("https://chocolatey.org/install.ps1"))

install:
  - cinst atom
  - cd %APPVEYOR_BUILD_FOLDER%
  - apm install
  # -------
  - cinst 7zip.commandline
  - cd %TEMP%
  - ps: Start-FileDownload "https://raw.githubusercontent.com/thomasjo/appveyor-texlive/master/texlive.7z"
  - 7za x texlive.7z -oC:\texlive -y
  - set Path=%Path%;C:\texlive\bin\win32

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - apm test
