version: "{build}"
os: Windows Server 2012 R2

test: off
deploy: off

init:
  - cmd: rd /s /q %CHOCOLATEYINSTALL%
  - ps: iex ((New-Object Net.WebClient).DownloadString("https://chocolatey.org/install.ps1"))

install:
  - cinst 7zip.commandline
  - cd %TEMP%
  - echo "Downloading portable TeX Live installation..."
  - ps: Start-FileDownload "https://raw.githubusercontent.com/thomasjo/appveyor-texlive/master/texlive.7z"
  - 7za x texlive.7z -oC:\ -y
  - set PATH=C:\texlive\bin\win32;%PATH%
  # -------
  - cinst atom
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm install"


build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - "%LOCALAPPDATA%/atom/bin/apm test --path %LOCALAPPDATA%/atom/bin/atom.cmd"
